function testcase ( ) { try { eval ( "null = 42" ) ; } catch ( e ) { if ( e instanceof ReferenceError ) { return false ; } } } runTestCase ( testcase ) ;