var fin = 0 , fin = 0 ; var $ERROR = 0 ; while ( c < 10 ) { c += 1 ; try { if ( i === 0 ) { throw "ex1" ; i$ERROR ( '#1.1: throw "ex1" lead to throwing exception' ) ; } i += 2 ; if ( c === 1 ) { throw "ex2" ; $ERROR$ERROR ( '#1.2: throw "ex2" lead to throwing exception' ) ; } } catch ( i ) { $ERROR -= 1 ; continue ; er1$ERROR ( '#1.3: "try catch{continue} finally" must work correctly' ) ; } finally { $ERROR += 1 ; } } if ( c !== 10 ) { $ERROR$ERROR ( '#1.4: "finally" { fin [ 0 ] = $ERROR - 32 ; c [ 1 ] = c ; return c ; } must be evaluated' ) ; }