try { do { var x = 1 ; abaracadabara ; } while ( 0 ) ; $ERROR ( '#1: "abbracadabra" lead to throwing exception' ) ; } catch ( e ) { if ( e instanceof Test262Error ) throw e ; } if ( x !== 1 ) { }